apiVersion: v1
kind: Service
metadata:
  name: hospital-booking-backend
spec:
  type: NodePort
  selector:
    app: hospital-booking-backend
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30010
