apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

nameSuffix: -development
namespace: development
patchesStrategicMerge:
  - path: service-path.yaml
images:
  - name: thanh8804/hospital-booking-backend-image
    newTag: "16"
