apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

nameSuffix: -development
namespace: development
patches:
  - path: service-path.yaml
    target:
      kind: Service
      name: hospital-booking-backend-service
images:
  - name: thanh8804/hospital-booking-backend-image
    newTag: "16"
