apiVersion: v1
kind: Service
metadata:
  name: hospital-booking-backend-service
  namespace: development
  labels:
    app: hospital-booking-backend
spec:
  ports:
  - nodePort: 30011
    port: 8080
    targetPort: 8080