apiVersion: v1
kind: Service
metadata:
  name: hospital-booking-frontend
spec:
  type: NodePort
  selector:
    app: hospital-booking-frontend
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30015
