resources:
  - ../../base

nameSuffix: -production

namespace: production
patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: hospital-booking-backend-deployment
images:
  - name: thanh8804/hospital-booking-backend-image
    newTag: "20"
# This file is intentionally left blank.